"Chime when Charging" section for macOS >= 10.13
herrbischoff/awesome-macos-command-line pull request #213
Opened 2020-10-03 06:19 UTC by ric-bianchi

This PR updates the section "Chime when Charging" for macOS >= 10.13 (High Sierra). 

By using the earlier instructions, the "chime" sound on the latest versions of macOS is not disabled and the `PowerChime` app restart as soon as the charger is connected. 

The new instructions fix the problem.

( Source: https://discussions.apple.com/thread/250339438?answerId=250640435022#250640435022 )

2020-10-03 06:19 UTC, ric-bianchi commented
Tested on macOS 10.14 (Mojave)

2020-10-03 10:57 UTC, NoahCardoza commented
Finally! I wasn't looking for this but saw it in an email update.

That sound was getting annoying fast.

2021-03-09 11:05 UTC, herrbischoff requested changes
Thank you for the suggestion. However, I would appreciate it, if you took the contribution guide and the existing style seriously. I had to flag every line of your pull request.

2021-03-09 11:05 UTC, herrbischoff commented on README.md
> +defaults write com.apple.PowerChime ChimeOnNoHardware -bool false; open /System/Library/CoreServices/PowerChime.app
Please change the code style to match the existing example.

2021-03-09 11:05 UTC, herrbischoff commented on README.md
> +defaults write com.apple.PowerChime ChimeOnNoHardware -bool true; killall PowerChime
Please change the code style to match the existing example.

2021-03-09 11:05 UTC, herrbischoff commented on README.md
> +From macOS 10.13 (High Sierra):
This needs to read `From macOS 10.13 (High Sierra) on` to match the style of existing entries.

2021-03-09 11:05 UTC, herrbischoff commented on README.md
> +For macOS <= 10.12 (Sierra):
This needs to read `Up to macOS 10.12 (Sierra)` to match the style of existing entries.

2021-03-22 22:00 UTC, herrbischoff commented
It's been almost two weeks and you have not replied. Closing.

2021-03-22 22:00 UTC, closed without merging